version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Euler"
    schedule:
      interval: "daily"
      time: "05:00"
  - package-ecosystem: "nuget"
    directory: "/Puzzles.Tests.FSharp"
    schedule:
      interval: "daily"
      time: "05:00"
